-- Juridence Database Schema for SQLite
-- Generated: 2025-09-30 09:05:15
-- Migrated from PostgreSQL

CREATE TABLE access_logs (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER,
    session_id TEXT,
    ip_address TEXT,
    user_agent TEXT,
    method TEXT,
    url TEXT,
    endpoint TEXT,
    status_code INTEGER,
    response_time INTEGER,
    request_size INTEGER,
    response_size INTEGER,
    referer TEXT,
    country TEXT,
    city TEXT,
    device_type TEXT,
    browser TEXT,
    os TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_logs (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER,
    session_id TEXT,
    activity_type TEXT,
    action TEXT,
    description TEXT,
    resource_type TEXT,
    resource_id TEXT,
    old_values TEXT,
    new_values TEXT,
    ip_address TEXT,
    user_agent TEXT,
    log_metadata TEXT,
    severity TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_chat_sessions (
    id INTEGER NOT NULL PRIMARY KEY,
    session_id TEXT NOT NULL,
    case_id INTEGER NOT NULL,
    user_id INTEGER,
    title TEXT,
    is_active INTEGER NOT NULL,
    messages TEXT,
    total_messages INTEGER NOT NULL,
    case_context_snapshot TEXT,
    ai_model_used TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settings TEXT
);

CREATE TABLE api_keys (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    key_prefix TEXT NOT NULL,
    permissions TEXT,
    rate_limit INTEGER,
    is_active INTEGER NOT NULL,
    last_used TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TEXT
);

CREATE TABLE audit_logs (
    id INTEGER NOT NULL PRIMARY KEY,
    table_name TEXT,
    record_id INTEGER,
    action TEXT,
    old_values TEXT,
    new_values TEXT,
    user_id INTEGER,
    timestamp TEXT,
    ip_address TEXT,
    user_agent TEXT
);

CREATE TABLE bank_analytics (
    id INTEGER NOT NULL PRIMARY KEY,
    bank_id INTEGER,
    risk_score INTEGER,
    risk_level TEXT,
    risk_factors TEXT,
    total_monetary_amount REAL,
    average_case_value REAL,
    financial_risk_level TEXT,
    primary_subject_matter TEXT,
    subject_matter_categories TEXT,
    legal_issues TEXT,
    financial_terms TEXT,
    regulatory_compliance_score INTEGER,
    customer_dispute_rate REAL,
    operational_risk_score INTEGER,
    credit_risk_exposure REAL,
    case_complexity_score INTEGER,
    success_rate REAL,
    last_updated TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bank_case_statistics (
    id INTEGER NOT NULL PRIMARY KEY,
    bank_id INTEGER,
    total_cases INTEGER,
    resolved_cases INTEGER,
    unresolved_cases INTEGER,
    favorable_cases INTEGER,
    unfavorable_cases INTEGER,
    mixed_cases INTEGER,
    case_outcome TEXT,
    last_updated TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE banks (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    logo_url TEXT,
    website TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    postal_code TEXT,
    bank_code TEXT,
    swift_code TEXT,
    license_number TEXT,
    established_date TEXT,
    bank_type TEXT,
    ownership_type TEXT,
    services TEXT,
    previous_names TEXT,
    branches_count INTEGER,
    atm_count INTEGER,
    total_assets REAL,
    net_worth REAL,
    rating TEXT,
    head_office_address TEXT,
    customer_service_phone TEXT,
    customer_service_email TEXT,
    has_mobile_app INTEGER,
    has_online_banking INTEGER,
    has_atm_services INTEGER,
    has_foreign_exchange INTEGER,
    is_active INTEGER,
    is_verified INTEGER,
    verification_date TEXT,
    verification_notes TEXT,
    search_count INTEGER,
    last_searched TEXT,
    created_at TEXT,
    updated_at TEXT,
    created_by INTEGER,
    updated_by INTEGER,
    description TEXT,
    notes TEXT,
    status TEXT
);

CREATE TABLE billing_summary (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    billing_period_start TEXT NOT NULL,
    billing_period_end TEXT NOT NULL,
    total_tokens INTEGER NOT NULL,
    total_api_calls INTEGER NOT NULL,
    total_searches INTEGER NOT NULL,
    total_ai_sessions INTEGER NOT NULL,
    total_cost REAL NOT NULL,
    ai_chat_cost REAL NOT NULL,
    search_cost REAL NOT NULL,
    api_cost REAL NOT NULL,
    tokens_per_search REAL,
    cost_per_search REAL,
    avg_response_time REAL,
    is_billed INTEGER NOT NULL,
    billing_date TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE case_hearings (
    id INTEGER NOT NULL PRIMARY KEY,
    case_id INTEGER,
    hearing_date TEXT,
    hearing_time TEXT,
    coram TEXT,
    remark TEXT,
    proceedings TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE case_mentions (
    id INTEGER NOT NULL PRIMARY KEY,
    case_id INTEGER NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id INTEGER NOT NULL,
    entity_name TEXT NOT NULL,
    mention_in_title INTEGER,
    mention_in_antagonist INTEGER,
    mention_in_protagonist INTEGER,
    mention_in_content INTEGER,
    mention_in_judgement INTEGER,
    mention_in_decision INTEGER,
    total_mentions INTEGER,
    created_at TEXT
);

CREATE TABLE case_metadata (
    id INTEGER NOT NULL PRIMARY KEY,
    case_id INTEGER NOT NULL,
    case_summary TEXT,
    summernote_content TEXT,
    case_type TEXT,
    area_of_law TEXT,
    keywords TEXT,
    judges TEXT,
    lawyers TEXT,
    related_people TEXT,
    protagonist TEXT,
    antagonist TEXT,
    organizations TEXT,
    banks_involved TEXT,
    insurance_involved TEXT,
    resolution_status TEXT,
    outcome TEXT,
    decision_type TEXT,
    monetary_amount REAL,
    statutes_cited TEXT,
    cases_cited TEXT,
    court_type TEXT,
    court_division TEXT,
    search_keywords TEXT,
    relevance_score REAL,
    is_processed INTEGER,
    created_at TEXT,
    updated_at TEXT,
    processed_at TEXT
);

CREATE TABLE case_search_index (
    id INTEGER NOT NULL PRIMARY KEY,
    case_id INTEGER NOT NULL,
    searchable_text TEXT NOT NULL,
    person_names TEXT,
    organization_names TEXT,
    keywords TEXT,
    word_count INTEGER,
    last_indexed TEXT
);

CREATE TABLE companies (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    logo_url TEXT,
    website TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    postal_code TEXT,
    type_of_company TEXT,
    district TEXT,
    date_of_incorporation TEXT,
    date_of_commencement TEXT,
    nature_of_business TEXT,
    registration_number TEXT,
    tax_identification_number TEXT,
    phone_number TEXT,
    directors TEXT,
    secretary TEXT,
    auditor TEXT,
    authorized_shares INTEGER,
    stated_capital REAL,
    shareholders TEXT,
    other_linked_companies TEXT,
    tin_number TEXT,
    established_date TEXT,
    company_type TEXT,
    industry TEXT,
    ownership_type TEXT,
    business_activities TEXT,
    previous_names TEXT,
    board_of_directors TEXT,
    key_personnel TEXT,
    subsidiaries TEXT,
    annual_revenue REAL,
    net_worth REAL,
    employee_count INTEGER,
    rating TEXT,
    head_office_address TEXT,
    customer_service_phone TEXT,
    customer_service_email TEXT,
    has_website INTEGER,
    has_social_media INTEGER,
    has_mobile_app INTEGER,
    is_active INTEGER,
    is_verified INTEGER,
    verification_date TEXT,
    verification_notes TEXT,
    search_count INTEGER,
    last_searched TEXT,
    created_at TEXT,
    updated_at TEXT,
    created_by INTEGER,
    updated_by INTEGER,
    description TEXT,
    notes TEXT,
    status TEXT
);

CREATE TABLE company_analytics (
    id INTEGER NOT NULL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    risk_score INTEGER,
    risk_level TEXT,
    risk_factors TEXT,
    total_monetary_amount REAL,
    average_case_value REAL,
    financial_risk_level TEXT,
    primary_subject_matter TEXT,
    subject_matter_categories TEXT,
    legal_issues TEXT,
    financial_terms TEXT,
    regulatory_compliance_score INTEGER,
    customer_dispute_rate REAL,
    operational_risk_score INTEGER,
    business_continuity_score INTEGER,
    market_risk_score INTEGER,
    credit_risk_score INTEGER,
    reputation_risk_score INTEGER,
    case_complexity_score INTEGER,
    success_rate REAL,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE company_case_statistics (
    id INTEGER NOT NULL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    total_cases INTEGER,
    resolved_cases INTEGER,
    unresolved_cases INTEGER,
    favorable_cases INTEGER,
    unfavorable_cases INTEGER,
    mixed_cases INTEGER,
    case_outcome TEXT,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE court_types (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    level TEXT NOT NULL,
    description TEXT,
    jurisdiction TEXT,
    region TEXT,
    address TEXT,
    contact_info TEXT,
    presiding_judge TEXT,
    established_date TEXT,
    is_active INTEGER NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    created_by TEXT,
    updated_by TEXT
);

CREATE TABLE courts (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    registry_name TEXT,
    court_type TEXT NOT NULL,
    region TEXT NOT NULL,
    location TEXT NOT NULL,
    address TEXT,
    city TEXT,
    district TEXT,
    latitude REAL,
    longitude REAL,
    google_place_id TEXT,
    area_coverage TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    website TEXT,
    court_picture_url TEXT,
    additional_images TEXT,
    operating_hours TEXT,
    is_active INTEGER NOT NULL,
    is_verified INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    created_by INTEGER,
    updated_by INTEGER,
    search_count INTEGER NOT NULL,
    last_searched TEXT,
    notes TEXT,
    status TEXT NOT NULL
);

CREATE TABLE error_logs (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER,
    session_id TEXT,
    error_type TEXT NOT NULL,
    error_message TEXT NOT NULL,
    stack_trace TEXT,
    url TEXT,
    method TEXT,
    status_code INTEGER,
    ip_address TEXT,
    user_agent TEXT,
    log_metadata TEXT,
    severity TEXT NOT NULL,
    resolved INTEGER NOT NULL,
    resolved_at TEXT,
    resolved_by INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE insurance (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    logo_url TEXT,
    website TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    postal_code TEXT,
    license_number TEXT,
    registration_number TEXT,
    established_date TEXT,
    insurance_type TEXT,
    ownership_type TEXT,
    services TEXT,
    previous_names TEXT,
    coverage_areas TEXT,
    branches_count INTEGER,
    agents_count INTEGER,
    total_assets REAL,
    net_worth REAL,
    premium_income REAL,
    claims_paid REAL,
    rating TEXT,
    head_office_address TEXT,
    customer_service_phone TEXT,
    customer_service_email TEXT,
    claims_phone TEXT,
    claims_email TEXT,
    has_mobile_app INTEGER,
    has_online_portal INTEGER,
    has_online_claims INTEGER,
    has_24_7_support INTEGER,
    specializes_in TEXT,
    target_market TEXT,
    is_active INTEGER,
    is_verified INTEGER,
    verification_date TEXT,
    verification_notes TEXT,
    search_count INTEGER,
    last_searched TEXT,
    created_at TEXT,
    updated_at TEXT,
    created_by INTEGER,
    updated_by INTEGER,
    description TEXT,
    notes TEXT,
    status TEXT
);

CREATE TABLE insurance_analytics (
    id INTEGER NOT NULL PRIMARY KEY,
    insurance_id INTEGER NOT NULL,
    risk_score INTEGER,
    risk_level TEXT,
    risk_factors TEXT,
    total_monetary_amount REAL,
    average_case_value REAL,
    financial_risk_level TEXT,
    primary_subject_matter TEXT,
    subject_matter_categories TEXT,
    legal_issues TEXT,
    financial_terms TEXT,
    regulatory_compliance_score INTEGER,
    customer_dispute_rate REAL,
    operational_risk_score INTEGER,
    claims_ratio REAL,
    underwriting_risk_score INTEGER,
    solvency_ratio REAL,
    premium_adequacy_score INTEGER,
    case_complexity_score INTEGER,
    success_rate REAL,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE insurance_case_statistics (
    id INTEGER NOT NULL PRIMARY KEY,
    insurance_id INTEGER NOT NULL,
    total_cases INTEGER,
    resolved_cases INTEGER,
    unresolved_cases INTEGER,
    favorable_cases INTEGER,
    unfavorable_cases INTEGER,
    mixed_cases INTEGER,
    case_outcome TEXT,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE judges (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    court_type TEXT,
    court_division TEXT,
    region TEXT,
    status TEXT NOT NULL,
    bio TEXT,
    appointment_date TEXT,
    retirement_date TEXT,
    contact_info TEXT,
    specializations TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    created_by TEXT,
    updated_by TEXT,
    is_active INTEGER NOT NULL
);

CREATE TABLE legal_history (
    id INTEGER NOT NULL PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id INTEGER NOT NULL,
    entity_name TEXT NOT NULL,
    case_id INTEGER NOT NULL,
    mention_type TEXT NOT NULL,
    mention_context TEXT,
    mention_count INTEGER,
    relevance_score REAL,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE legal_search_index (
    id INTEGER NOT NULL PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id INTEGER NOT NULL,
    entity_name TEXT NOT NULL,
    search_terms TEXT NOT NULL,
    case_count INTEGER,
    last_updated TEXT,
    is_active INTEGER
);

CREATE TABLE login_sessions (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    session_token TEXT NOT NULL,
    refresh_token TEXT,
    ip_address TEXT,
    user_agent TEXT,
    country TEXT,
    city TEXT,
    is_active INTEGER NOT NULL,
    is_mobile INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT NOT NULL
);

CREATE TABLE notification_preferences (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    email_notifications INTEGER NOT NULL,
    email_success INTEGER NOT NULL,
    email_info INTEGER NOT NULL,
    email_warning INTEGER NOT NULL,
    email_error INTEGER NOT NULL,
    in_app_notifications INTEGER NOT NULL,
    in_app_success INTEGER NOT NULL,
    in_app_info INTEGER NOT NULL,
    in_app_warning INTEGER NOT NULL,
    in_app_error INTEGER NOT NULL,
    subscription_notifications INTEGER NOT NULL,
    case_notifications INTEGER NOT NULL,
    billing_notifications INTEGER NOT NULL,
    system_notifications INTEGER NOT NULL,
    security_notifications INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL,
    priority TEXT NOT NULL,
    status TEXT NOT NULL,
    category TEXT,
    action_url TEXT,
    notification_data TEXT,
    is_email_sent INTEGER NOT NULL,
    is_sms_sent INTEGER NOT NULL,
    is_push_sent INTEGER NOT NULL,
    action_text TEXT,
    notification_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TEXT,
    archived_at TEXT,
    expires_at TEXT
);

CREATE TABLE payments (
    id INTEGER NOT NULL PRIMARY KEY,
    subscription_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    stripe_payment_intent_id TEXT,
    stripe_charge_id TEXT,
    payment_method TEXT,
    last_four TEXT,
    billing_period_start TEXT NOT NULL,
    billing_period_end TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TEXT
);

CREATE TABLE people (
    id INTEGER NOT NULL PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    previous_names TEXT,
    date_of_birth TEXT,
    date_of_death TEXT,
    id_number TEXT,
    phone_number TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    postal_code TEXT,
    risk_level TEXT,
    risk_score REAL,
    case_count INTEGER,
    case_types TEXT,
    court_records TEXT,
    occupation TEXT,
    employer TEXT,
    organization TEXT,
    job_title TEXT,
    marital_status TEXT,
    spouse_name TEXT,
    children_count INTEGER,
    emergency_contact TEXT,
    emergency_phone TEXT,
    nationality TEXT,
    gender TEXT,
    education_level TEXT,
    languages TEXT,
    is_verified INTEGER,
    verification_date TEXT,
    verification_notes TEXT,
    last_searched TEXT,
    search_count INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    created_by INTEGER,
    updated_by INTEGER,
    status TEXT,
    notes TEXT
);

CREATE TABLE permissions (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    resource TEXT NOT NULL,
    action TEXT NOT NULL,
    is_system_permission INTEGER NOT NULL,
    is_active INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER,
    updated_by INTEGER
);

CREATE TABLE person_analytics (
    id INTEGER NOT NULL PRIMARY KEY,
    person_id INTEGER NOT NULL,
    risk_score INTEGER,
    risk_level TEXT,
    risk_factors TEXT,
    total_monetary_amount REAL,
    average_case_value REAL,
    financial_risk_level TEXT,
    primary_subject_matter TEXT,
    subject_matter_categories TEXT,
    legal_issues TEXT,
    financial_terms TEXT,
    case_complexity_score INTEGER,
    success_rate REAL,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE person_case_statistics (
    id INTEGER NOT NULL PRIMARY KEY,
    person_id INTEGER NOT NULL,
    total_cases INTEGER,
    resolved_cases INTEGER,
    unresolved_cases INTEGER,
    favorable_cases INTEGER,
    unfavorable_cases INTEGER,
    mixed_cases INTEGER,
    case_outcome TEXT,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reported_cases (
    id INTEGER NOT NULL PRIMARY KEY,
    title TEXT,
    suit_reference_number TEXT,
    date TEXT,
    presiding_judge TEXT,
    statutes_cited TEXT,
    cases_cited TEXT,
    lawyers TEXT,
    commentary TEXT,
    headnotes TEXT,
    town TEXT,
    region TEXT,
    dl_citation_no TEXT,
    created_by TEXT,
    updated_by TEXT,
    file_url TEXT,
    judgement TEXT,
    year TEXT,
    created_at TEXT,
    updated_at TEXT,
    type TEXT,
    firebase_url TEXT,
    summernote TEXT,
    detail_content TEXT,
    decision TEXT,
    antagonist TEXT,
    protagonist TEXT,
    citation TEXT,
    court_type TEXT,
    court_division TEXT,
    file_name TEXT,
    c_t INTEGER,
    judgement_by TEXT,
    status TEXT,
    case_summary TEXT,
    area_of_law TEXT,
    keywords_phrases TEXT,
    published INTEGER,
    dl_type TEXT,
    academic_programme_id TEXT,
    opinion_by TEXT,
    conclusion TEXT,
    ai_case_outcome TEXT,
    ai_court_orders TEXT,
    ai_financial_impact TEXT,
    ai_detailed_outcome TEXT,
    ai_summary_generated_at TEXT,
    ai_summary_version TEXT
);

CREATE TABLE request_details (
    id INTEGER NOT NULL PRIMARY KEY,
    request_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id INTEGER,
    entity_name TEXT,
    case_id INTEGER,
    case_suit_number TEXT,
    message TEXT,
    status TEXT,
    requester_name TEXT,
    requester_email TEXT,
    requester_phone TEXT,
    requester_organization TEXT,
    assigned_to TEXT,
    admin_notes TEXT,
    response_message TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    completed_at TEXT,
    priority TEXT,
    is_urgent INTEGER,
    source_ip TEXT,
    user_agent TEXT,
    referrer TEXT
);

CREATE TABLE roles (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    description TEXT,
    is_system_role INTEGER NOT NULL,
    is_active INTEGER NOT NULL,
    permissions TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER,
    updated_by INTEGER
);

CREATE TABLE security_events (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    description TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    country TEXT,
    city TEXT,
    security_metadata TEXT,
    risk_score INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE security_logs (
    id INTEGER NOT NULL PRIMARY KEY,
    event_type TEXT,
    severity TEXT,
    message TEXT,
    user_id INTEGER,
    ip_address TEXT,
    user_agent TEXT,
    metadata TEXT,
    timestamp TEXT
);

CREATE TABLE settings (
    id INTEGER NOT NULL PRIMARY KEY,
    key TEXT NOT NULL,
    category TEXT NOT NULL,
    value TEXT,
    value_type TEXT NOT NULL,
    description TEXT,
    is_public INTEGER NOT NULL,
    is_editable INTEGER NOT NULL,
    is_required INTEGER NOT NULL,
    validation_rules TEXT,
    default_value TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER
);

CREATE TABLE subscription_plans (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    slug TEXT NOT NULL,
    price_monthly REAL NOT NULL,
    price_yearly REAL,
    currency TEXT NOT NULL,
    max_users INTEGER NOT NULL,
    max_cases_per_month INTEGER NOT NULL,
    max_storage_gb REAL NOT NULL,
    features TEXT,
    is_active INTEGER NOT NULL,
    is_popular INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscription_requests (
    id INTEGER NOT NULL PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    billing_cycle TEXT NOT NULL,
    requested_by INTEGER,
    status TEXT NOT NULL,
    notes TEXT,
    reviewed_by INTEGER,
    reviewed_at TEXT,
    admin_notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscriptions (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    plan TEXT NOT NULL,
    status TEXT NOT NULL,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    billing_cycle TEXT NOT NULL,
    start_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_date TEXT,
    trial_end TEXT,
    cancelled_at TEXT,
    stripe_subscription_id TEXT,
    stripe_customer_id TEXT,
    features TEXT,
    limits TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tenant_settings (
    id INTEGER NOT NULL PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    value_type TEXT NOT NULL,
    description TEXT,
    is_public INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER
);

CREATE TABLE tenants (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    website TEXT,
    email TEXT,
    phone TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    postal_code TEXT,
    logo_url TEXT,
    primary_color TEXT NOT NULL,
    secondary_color TEXT NOT NULL,
    accent_color TEXT NOT NULL,
    font_family TEXT NOT NULL,
    app_name TEXT NOT NULL,
    app_tagline TEXT NOT NULL,
    favicon_url TEXT,
    subscription_plan_id INTEGER,
    subscription_status TEXT NOT NULL,
    trial_ends_at TEXT,
    subscription_ends_at TEXT,
    max_users INTEGER NOT NULL,
    max_cases_per_month INTEGER NOT NULL,
    max_storage_gb REAL NOT NULL,
    features_enabled TEXT,
    is_active INTEGER NOT NULL,
    is_approved INTEGER NOT NULL,
    is_verified INTEGER NOT NULL,
    admin_user_id INTEGER,
    contact_person_name TEXT,
    contact_person_email TEXT,
    contact_person_phone TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER,
    updated_by INTEGER
);

CREATE TABLE two_factor_auth (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    is_enabled INTEGER NOT NULL,
    method TEXT,
    phone_number TEXT,
    sms_verified INTEGER NOT NULL,
    secret_key TEXT,
    backup_codes TEXT,
    email_verified INTEGER NOT NULL,
    recovery_codes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used TEXT
);

CREATE TABLE usage_records (
    id INTEGER NOT NULL PRIMARY KEY,
    subscription_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    resource_type TEXT NOT NULL,
    count INTEGER NOT NULL,
    usage_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usage_tracking (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER,
    session_id TEXT,
    endpoint TEXT NOT NULL,
    method TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    tokens_used INTEGER,
    api_calls INTEGER,
    response_time_ms INTEGER,
    data_processed INTEGER,
    estimated_cost REAL,
    cost_per_token REAL,
    cost_per_api_call REAL,
    query TEXT,
    filters_applied TEXT,
    results_count INTEGER,
    ai_model TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    ip_address TEXT,
    user_agent TEXT,
    referer TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    assigned_by INTEGER,
    assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT,
    is_active INTEGER NOT NULL,
    notes TEXT
);

CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY,
    email TEXT NOT NULL,
    username TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone_number TEXT,
    hashed_password TEXT,
    is_verified INTEGER NOT NULL,
    verification_token TEXT,
    google_id TEXT,
    google_email TEXT,
    oauth_provider TEXT,
    reset_token TEXT,
    reset_token_expires TEXT,
    role TEXT NOT NULL,
    status TEXT NOT NULL,
    is_admin INTEGER NOT NULL,
    tenant_id INTEGER,
    is_tenant_admin INTEGER NOT NULL,
    profile_picture TEXT,
    bio TEXT,
    organization TEXT,
    job_title TEXT,
    email_notifications INTEGER NOT NULL,
    sms_notifications INTEGER NOT NULL,
    language TEXT NOT NULL,
    timezone TEXT NOT NULL,
    subscription_plan TEXT,
    subscription_expires TEXT,
    is_premium INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TEXT,
    failed_login_attempts INTEGER NOT NULL,
    locked_until TEXT
);
