name: case-search-app
services:
  # Backend API Service
  - name: case-search-backend
    source_dir: /backend
    github:
      repo: your-username/case-search-html
      branch: main
      deploy_on_push: true
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALGORITHM
        value: HS256
        scope: RUN_TIME
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
        scope: RUN_TIME
      - key: CORS_ORIGINS
        value: https://case-search-frontend.ondigitalocean.app
        scope: RUN_TIME
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        scope: RUN_TIME
        type: SECRET

  # Frontend Static Site
  - name: case-search-frontend
    source_dir: /
    github:
      repo: your-username/case-search-html
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npx serve -s build -l 3000
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: https://case-search-backend.ondigitalocean.app
        scope: RUN_TIME
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        scope: RUN_TIME
        type: SECRET

databases:
  - name: case-search-db
    engine: MYSQL
    version: "8"
    size: db-s-1vcpu-1gb
    num_nodes: 1
